# Generated by Django 4.2.7 on 2025-03-18 16:53

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_profile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=20, prefix='', unique=True),
        ),
    ]
